Joke.create(lead: "What do you call a cow with no legs?", punchline: "Ground beef!")
Joke.create(lead: "What's the best way to carve wood?", punchline: "Whittle by whittle!")
Joke.create(lead: "This bouncy castle costs twice as much this year.", punchline: "That's what I call inflation!")
Joke.create(lead: "Why can't you hear a pterodactyl use the bathroom?", punchline: "Because his pee is silent!")
Joke.create(lead: "Want to hear a joke about construction?", punchline: "I'm still working on it!")
Joke.create(lead: "I warned you not to eat that Play-doh spaghetti.", punchline: "It's an impasta!")
Joke.create(lead: "Why do people think the shovle was such an important invention?", punchline: "Because it's ground-breaking!")
Joke.create(lead: "A man told me he hadn't gone to the bathroom in years.", punchline: "I reckon he's full of crap!")
Joke.create(lead: "You can't tell too many lightbulb jokes.", punchline: "You'll get burned out!")
Joke.create(lead: "I don't tell that lasagna joke anymore.", punchline: "It was too cheesy!")
Joke.create(lead: "When did you mother go to the dentist?", punchline: "Tooth hurt-y!")
Joke.create(lead: "Did you hear about the guy who invented LifeSavers?", punchline: "They say he made a mint!")
Joke.create(lead: "Chicken panini walks into a bar and orders a beer.", punchline: "Bartender says 'Sorry, we don't serve food here!")
Joke.create(lead: "Why did the tissue start dancing?", punchline: "It got a little boogie in it!")
Joke.create(lead: "Two peanuts left for a party, but one didn't make it.", punchline: "It was assaulted!")
Joke.create(lead: "Sorry, Junior... I got fired from the calendar factory today.", punchline: "They don't like it when you take days off.")
Joke.create(lead: "I dreampt I was a muffle last night.", punchline: "I woke up exhausted!")
Joke.create(lead: "I just saw a great show about beavers.", punchline: "Best dam show I'd ever seen!")
Joke.create(lead: "Why can't your bike stay up by itself?", punchline: "It's two tired!")
Joke.create(lead: "Don't trust atoms.", punchline: "They make up everything!")
Joke.create(lead: "I used to hate facial hair...", punchline: "but then it grew on me!")
Joke.create(lead: "What does an annoying pepper do?", punchline: "It get's jalapeño face!")
Joke.create(lead: "Why won't your nose ever grow twelve inches long?", punchline: "Because then it would be a foot!")
Joke.create(lead: "What do you get when you cross a snowman and a vampire?", punchline: "Frostbite!")
Joke.create(lead: "Two satellites got married.", punchline: "The ceremony was boring, but the reception was incredible!")
Joke.create(lead: "Did you hear about the explosion at the cheese factory?", punchline: "Nothing was left but de brie!")
Joke.create(lead: "You know why crabs never give to charity?", punchline: "They're shellfish!")
Joke.create(lead: "Why did the scarecrow win an award?", punchline: "He was outstanding in his field!")
Joke.create(lead: "What did the buffalo say to his as he left for college?", punchline: "Bison!")
Joke.create(lead: "Your mom and I had the most emotional wedding...", punchline: "even the cake was in tiers!")
Joke.create(lead: "Why did the coffee file a police report?", punchline: "It got mugged!")
Joke.create(lead: "Have you heard of the band, 1023MB?", punchline: "They haven't had a gig yet!")
Joke.create(lead: "I wouldn't buy anything with velcro.", punchline: "It's all a rip-off!")
Joke.create(lead: "Did you hear about the restaurant on the moon?", punchline: "Great food, but no atmosphere!")
Joke.create(lead: "When you grow up, you'll thank all the sidewalks...", punchline: "for keeping you off the streets!")
